title: [Yolanda Sukloff](http://www.linkedin.com/in/yolandasukloff)
logo: "C:\Users\yolan\OneDrive\Pictures\Saved Pictures\YolandaSukloff.png"
description: Healthcare Data Analyst
show_downloads: true
theme: jekyll-theme-minimal
